<?php 
include('../includes/auth_check.php');
include('../config/db.php');

if ($_SESSION['role'] !== 'Admin') {
    echo "<script>
            alert('Access denied. Admin only.');
            window.location.href='/patient_tracking_system/dashboard/index.php';
          </script>";
    exit();
}

$filename = "patient_tracking_backup_" . date("Y-m-d_H-i-s") . ".csv";

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=' . $filename);

$output = fopen("php://output", "w");

fputcsv($output, array("PATIENT TRACKING SYSTEM BACKUP"));
fputcsv($output, array("Generated On", date("Y-m-d H:i:s")));
fputcsv($output, array("Generated By", $_SESSION['fullname']));
fputcsv($output, array(""));

fputcsv($output, array("PATIENTS TABLE"));
fputcsv($output, array(
    "ID",
    "Patient ID",
    "Full Name",
    "Gender",
    "Age",
    "Phone",
    "Location",
    "QR Code",
    "Created At"
));

$patients = mysqli_query($conn, "SELECT * FROM patients ORDER BY id ASC");

while ($row = mysqli_fetch_assoc($patients)) {
    fputcsv($output, array(
        $row['id'],
        $row['patient_id'],
        $row['fullname'],
        $row['gender'],
        $row['age'],
        $row['phone'],
        $row['location'],
        $row['qr_code'],
        $row['created_at']
    ));
}

fputcsv($output, array(""));
fputcsv($output, array("ATTENDANCE TABLE"));
fputcsv($output, array(
    "ID",
    "Patient ID",
    "Visit Date",
    "Service Given",
    "Notes"
));

$attendance = mysqli_query($conn, "SELECT * FROM attendance ORDER BY id ASC");

while ($row = mysqli_fetch_assoc($attendance)) {
    fputcsv($output, array(
        $row['id'],
        $row['patient_id'],
        $row['visit_date'],
        $row['service_given'],
        $row['notes']
    ));
}

fputcsv($output, array(""));
fputcsv($output, array("USERS TABLE"));
fputcsv($output, array(
    "ID",
    "Full Name",
    "Email",
    "Role"
));

$users = mysqli_query($conn, "SELECT id, fullname, email, role FROM users ORDER BY id ASC");

while ($row = mysqli_fetch_assoc($users)) {
    fputcsv($output, array(
        $row['id'],
        $row['fullname'],
        $row['email'],
        $row['role']
    ));
}

fputcsv($output, array(""));
fputcsv($output, array("AUDIT LOGS TABLE"));
fputcsv($output, array(
    "ID",
    "User Name",
    "User Role",
    "Action",
    "Log Date"
));

$audit_logs = mysqli_query($conn, "SELECT * FROM audit_logs ORDER BY id ASC");

while ($row = mysqli_fetch_assoc($audit_logs)) {
    fputcsv($output, array(
        $row['id'],
        $row['user_name'],
        $row['user_role'],
        $row['action'],
        $row['log_date']
    ));
}

fclose($output);
exit();
?>